### ISSUE TITLE
Add all flipper feature to preview

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#158]
All features of the paid flipper (eg filter) should be visible in the preview as well.
The filters should be disabled (except auto scroll, which should be on by default)
When hovering the filters the tool tip "premium users only" should appear.
All users can call `subFlip` but non premium only get flips with a 5 min delay.
Its important that new visitors see the stream-flow of new flips.

**Comment by Ekwav** [comment]
Updated issue to reflect critic of @matthias-luger

**Comment by matthias-luger** [comment]
Should not be implemented

**Comment by Ekwav** [comment]
Turns out this was already implemented without any restrictions (a bug)
I will restrict the features to the level we agreed to.
