### ISSUE TITLE
Detect page reloads and display popup

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#177]
Our analytics suggests that a lot of users reload pages.
As we make heavy use of caches this has mostly no affect.
A overlay dialog should be created asking the user why he just reloaded with multiple choice answers.
- I want new information (noting the subscription feature)
- Something broke (stating that we would like to fix it and asking for feedback)
- Other issue (asking for feedback via discord)

Reloads can be checked via 
`performance.getEntriesByType("navigation")[0].type`
Every action should have a corresponding tracking event.

**Comment by matthias-luger** [comment]
Waiting for https://github.com/Coflnet/internal/issues/14
