### ISSUE TITLE
Request player heads in same size

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#222]
Player heads are currently requested in various resolutions.
This adds unnecessary requests to page loads.
All player heads should be loaded with size `8`.
This affects at least search, player details, auction details and the landing page,
To prevent the browser from blurring the image the `css` for player heads should be set to:
```
image-rendering: pixelated;
image-rendering: crisp-edges;
```
`pixelated` is for chrome 
`crisp-edges` is for firefox

**Comment by matthias-luger** [comment]
@Ekwav how does this affect the player details?
