### ISSUE TITLE
Improve page titles

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#226]
Update the page title to better reflect what is on the page.
Player pages only have the player name in the title.
This should be expanded to `Auctions and bids from XY in the hypixel skyblock ah`
Item pages should have the title.
`Auction Price tracker for XY in hypixel skyblock`
Also update the meta description of the html when navigating in react.
Furthermore reset/change the title when navigating to other pages such as `/flipper` currently the pages title stays the same which can be confusing.

**Comment by matthias-luger** [comment]
@Ekwav ideas for better meta descriptions?
