### ISSUE TITLE
Improve flipper performance

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#242]
The flipper gets slow (and sometimes crashes the tab) after more than a thousand flips.
This should be avoided at all cost.
The main bottleneck seems to be cpu time.
This is likely caused by aggregate functions such as `filter` and `map` which always process the whole list.
Please improve the flippers performance to support at least 10k flips, and start deleting flips over that mark.

**Comment by matthias-luger** [comment]
I improved the performance by minimizing rerenders and looping through the flips.
To further improve the performance i fried to only rerender the page every 5 new flips. This also increased the performance a bit.

Still the page starts lagging at around 1k flips. Is that enough?
