### ISSUE TITLE
Navigating to an item fills the history

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#250]
Steps to reproduce.
1. Search for an item
2. Press back

No visible navigation occured (the url changes to include an empty filter)
Navigation is only done after two additional back clicks.

**Comment by Ekwav** [comment]
This issue occurs again on the `next` branch

**Comment by matthias-luger** [comment]
Spent a lot of time on this. I have no idea why a new entry is created. I already use the router.replace method.
I tried a lot of different ways, but it would either break the navigation completely or create an additional history entry...

Things I tried:
- using replace with the modified router object
- using replace with a newly build URL object
- using replace with a url object
- using the native javascript location.replace
- using URLSearchParams to build the url and use the methods above

**Comment by Ekwav** [comment]
Issue doesn't occur anymore in production :)
