### ISSUE TITLE
Allow non premium users to use all filters

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#262]
I still think that non-premium users should have a chance to use the `BIN` and `not SOLD` filters. 
Please allow them to check the filter after 1-5 min on the site (preferably with a countdown).
It should not be too annoying to use the free flipper.
And after more than a minute everyone got it, that premium would be better but decided not to get it.
This is the same method as hypixel uses for daily rewards where you have to watch a 30sec youtube video before you can claim the reward.

**Comment by matthias-luger** [comment]
Once again I disagree with this feature. 👎
