### ISSUE TITLE
Connection with minecraft account

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#283]
To advance some current and make some future features possible the backend needs to know what minecraft account corresponds to a user. 
The `conMc(uuid)` was created for this. It returns a number `1-999`. 
The user should put up or bid on an auction with the last 3 digits set to that number to verify that he owns that minecraft account.
The option to connect a minecraft account is best suited for `/player/{uuid}`

**Comment by matthias-luger** [comment]
The UI stands so far. But we have to further improve this. As it is now you dont event know if you are connected and it doesnt provide any value. 

Also: I tried it and it didnt seem to work
