### ISSUE TITLE
Open select when add filter is clicked

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#286]
It currently takes two clicks to add a filter. 
This should be reduced to one by opening the select when `(+) add filter` is clicked.

**Comment by matthias-luger** [comment]
This does not seem possible: https://stackoverflow.com/questions/430237/is-it-possible-to-use-js-to-open-an-html-select-to-show-its-option-list

It was possible by emulating a click but doesnt seem to work in modern browsers anymore

**Comment by Ekwav** [comment]
I don't quite understand.
Why would you need JavaScript to click on it?
You make the default element of the select `(+) Add filter` and when a user clicks on it the drop-down is displayed by the browser, isn't it?

**Comment by Ekwav** [comment]
Also, the example works as well
![Screenshot_20210724-011110.png](https://user-images.githubusercontent.com/16632490/126849424-8723622b-5228-4848-83f1-7580beb3a998.png)
