### ISSUE TITLE
Figure out what glai wants

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#318]
glai wants a QOL feature to calculate how much an upgrade would cost.
He suggested this https://docs.google.com/spreadsheets/d/1gIwx6bNn3FUub0sZYE2sYE7t7XV74BccpoJ9Vs5aKpA/edit#gid=856450625
TODO:
figure out how to calculate the price of upgrades

**Comment by matthias-luger** [comment]
Upgrade prices will be used in the not so near future for Crafting flips.
That any many other flip variants (npc flip, reverse npc flip, upgrade flip, ...) will be implemented with or after the Task-feature.
For now, this wont be implemented
