### ISSUE TITLE
Add /devices Site

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#37]
Site content:
* List all devices (Command: `getDevices`)
* Option to delete each device via a bin icon (Command: `deleteDevice(deviceName)`)
* Option to send Notification to find out wich device it is (Command: `testNotification(deviceName)`)
* Option to add/rename a device (Command: `addDevice`). Because the name is also the identifier renaming should delete and recreate a device.

**Comment by Ekwav** [comment]
Currently devices are added with an empty name, when pressing the "subscribe" button after the google-login.   
Maybe the default name of a device should be the active item.

**Comment by Ekwav** [comment]
the relevant apis were partially removed.
if anyone wants to implement this please contact me first.

**Comment by matthias-luger** [comment]
@Ekwav I want to add this. I hereby contacted you :)

**Comment by Ekwav** [comment]
I added it to the   [api](https://sky.coflnet.com/api) currently valid target tyoes are `FIREBASE` and `DISCORDWEBHOOK` you can test them via the according endpoint.  
The subscription listeners themselves can be subscribed to (you would need the id from the (old) subscription to create a notification subscription) The previous subscription/notification system turned into a `source` for the event-broker (the system that now sends the notifications next to webhooks, in game messages and potentially email
