### ISSUE TITLE
Show if new flips are coming

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/hypixel-react#424]

**Comment by matthias-luger** [comment]
Waiting for https://github.com/Coflnet/SkyCommands/issues/4

**Comment by Ekwav** [comment]
Implemented https://sky-commands.coflnet.com/api/flip/update/when

**Comment by matthias-luger** [comment]
Gibt Error 405 bzw. CORS Fehler zurück.

**Comment by matthias-luger** [comment]
@Ekwav I am not sure about this:
![image](https://user-images.githubusercontent.com/58751503/137569948-b747fd01-f71b-4ce4-9811-4f2636618fd8.png)

**Comment by matthias-luger** [comment]
@Ekwav bekomme teilweise 10min verzögerte Zeiten? Liegt das an mir?
![image](https://user-images.githubusercontent.com/58751503/139190563-c4c0c7c9-7041-4071-8213-e3fe855eff4f.png)

**Comment by Ekwav** [comment]
> @Ekwav bekomme teilweise 10min verzögerte Zeiten? Liegt das an mir? ![image](https://user-images.githubusercontent.com/58751503/139190563-c4c0c7c9-7041-4071-8213-e3fe855eff4f.png)

Nope, thats the time the last update happened, it can be delayed by up to 30min.
I expected you to just use the seconds of that time because the api updates every minute
Also see https://github.com/Coflnet/SkyCommands/issues/4#issuecomment-920630323

**Comment by Ekwav** [comment]
> @Ekwav bekomme teilweise 10min verzögerte Zeiten? Liegt das an mir? ![image](https://user-images.githubusercontent.com/58751503/139190563-c4c0c7c9-7041-4071-8213-e3fe855eff4f.png)

Nope, thats the time the last update happened, it can be delayed by up to 30min.
I expected you to just use the seconds of that time because the api updates every minute
Also see https://github.com/Coflnet/SkyCommands/issues/4#issuecomment-920630323
