### ISSUE TITLE
Focus the search bar on starting page 

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/hypixel-react#446]
I don't want to click to do a search.
The searchbar should be focused on page load

**Comment by Ekwav** [comment]
This should only happen `on starting page` as written in the title.
The current implementation triggers the mobile virtual keyboard on every navigation

**Comment by matthias-luger** [comment]
On which device does this occur. It doesnt open the virtual keyboard for me (that should be the default behavior).

**Comment by Ekwav** [comment]
> On which device does this occur. It doesnt open the virtual keyboard for me (that should be the default behavior).

At least mine (CUBOT POWER android 8.1) will try to test on more devices

**Comment by Ekwav** [comment]
This also happens on 
realme 8 android 11
